# Use Python as the base image 
FROM python:3.10
# Define the working directory
WORKDIR /app
# Copy the application code into the container
COPY . /app
# Install dependencies
RUN pip install -r requirements.txt
# Expose the application port
EXPOSE 8000
# Set the startup command
CMD ["python", "app.py", "--host", "0.0.0.0", "--port", "8000"]